language: c
services: docker
os: linux
env:
  - IMAGE=linux-x64
  # - IMAGE=windows-x86
  - IMAGE=windows-x64
  # - IMAGE=linux-x86
  - IMAGE=android-arm
# - IMAGE=browser-asmjs
script:
  - bash <(curl -s https://raw.githubusercontent.com/makiolo/cmaki_scripts/master/docker.sh)
  - ./bin/cmaki_emulator.sh ./bin/cmaki_identifier parm1 parm2 parm3
 - WINEARCH=win64 ./bin/cmaki_identifier parm1 parm2 parm3
 - WINEARCH=win32 ./bin/cmaki_identifier parm1 parm2 parm3
