sudo: required
dist: trusty

language: c
cache: ccache

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
            - lcov
            - libmysqlcppconn-dev
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
            - libmysqlcppconn-dev
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
            - libmysqlcppconn-dev
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Release
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
            - valgrind
            - libmysqlcppconn-dev
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Release

    # Xcode 7.3 (clang)
    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Debug
      osx_image: xcode7.3

    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Release
      osx_image: xcode7.3

script:
  - npm install
  # - npm test
  - bin/cmaki_identifier
  - CMAKI_INFO=ALL bin/cmaki_identifier
  - CMAKI_INFO=ALL CMAKI_ENTROPY=coverage_version bin/cmaki_identifier
  - CMAKI_INFO=SO bin/cmaki_identifier
  - CMAKI_INFO=ARCH bin/cmaki_identifier
  - CMAKI_INFO=COMPILER bin/cmaki_identifier
