version: 1.0.{build}

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

install:
  - cmd: git submodule update --init --recursive
  - cmd: pip install pyyaml
  - cmd: pip install poster

build_script:
  - cmd: set || exit 0
  # TODO: use bootstrap.cmd
  - cmd: git clone https://github.com/makiolo/cmaki.git
  - cmd: git clone https://github.com/makiolo/cmaki_generator.git
  - cmd: git clone https://github.com/boostorg/predef.git boostorg_predef
  - cmd: call cmaki\setup.cmd
  - cmd: call cmaki\compile.cmd
  - cmd: call cmaki\tests.cmd
