#!/bin/bash
if [ ! -d "boostorg_predef" ]; then
	git clone -q https://github.com/boostorg/predef.git boostorg_predef
fi
curl -s https://raw.githubusercontent.com/makiolo/cmaki/master/setup.sh | bash
curl -s https://raw.githubusercontent.com/makiolo/cmaki/master/compile.sh | bash

